ALTER TABLE "Blog"
  ADD COLUMN IF NOT EXISTS "authorName" TEXT NOT NULL DEFAULT 'Smartest Store KE',
  ADD COLUMN IF NOT EXISTS "authorAvatarUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "category" TEXT,
  ADD COLUMN IF NOT EXISTS "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
